name = "report-service"
main = "dist/main.js"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]

account_id = "96860cdf1dd74618ce76b038cb18d733"
workers_dev = true

[vars]
PORT = "3000"
NODE_ENV = "production"
